### PR TITLE
Now works in Safari and set utf-8 with BOM encoding

### PR DESCRIPTION
**Pull request by Ivan-Feofanov**

### CODE REVIEW

**Comment by rubo77** [comment]
Can you Please refractor this without changing the indention?

Use `git --amend`

**Comment by Ivan-Feofanov** [comment]
Done.

**Comment by rubo77** [comment]
better, but still not completely correct. see "files changed" in this PR: https://github.com/zachwick/TableCSVExport/pull/11/files

please use exactly 4 spaces as indention on each level.

It seems, like there was a bug where there were 8 spaces in one part, that can be corrected too.

And when you are finished, plese rebase this as only one commit.

**Comment by Ivan-Feofanov** [comment]
I think now it's allright with intendation. I use only 4 space to intend.

**Comment by zachwick** [comment]
Thanks a bunch for this @Ivan-Feofanov and @rubo77! I'm sorry that I am just now merging it in - it looks like I inadvertently turned off notifications for all repos, not just some.

**Pull request merged**
